# This is a basic workflow to help you get started with Actions

name: shasta

# Controls when the action will run.
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-shasta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.5
    - name: verify conda
      run: |
          conda --version
          which python
    - name: setup java
      uses: actions/setup-java@v1
    - name: verify java
      run: java -version
    - name: install cromwell and womtool
      run: |
          wget https://github.com/broadinstitute/cromwell/releases/download/58/cromwell-58.jar
          wget https://github.com/broadinstitute/cromwell/releases/download/58/womtool-58.jar
    - name: verify cromwell
      run: |
          java -jar cromwell-58.jar
          java -jar womtool-58.jar
    # - name: Install womtool
    #   run: conda install -yq -c bioconda womtool
    # - name: validate with womtool
    #   run: $CONDA/bin/womtool validate Shasta/Shasta.wdl
