# This is a basic workflow to help you get started with Actions

name: shasta

# Controls when the action will run.
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-shasta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.5
    - name: verify conda
      run: |
          conda --version
          which python
    - name: Install cromwell and womtool
      run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda create -yq -n cromwell cromwell
    - name: Cromwell enviornment
      run: conda activate cromwell
    - name: validate with womtool
      run: |
          ls
          cd ./Shasta
          womtool validate ./Shasta.wdl
